steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/semilleros-de-sentido-landing-v1:latest', '-t', 'gcr.io/$PROJECT_ID/semilleros-de-sentido-landing-v1:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/semilleros-de-sentido-landing-v1:$BUILD_ID', '.']
  id: 'build-image-semilleros-de-sentido-landing-v1'
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/semilleros-de-sentido-landing-v1:$COMMIT_SHA']
  id: 'push-image-to-container-registry'
  waitFor: ['build-image-semilleros-de-sentido-landing-v1']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'semilleros-de-sentido-landing-v1'
  - '--image'
  - 'gcr.io/$PROJECT_ID/semilleros-de-sentido-landing-v1:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--port'
  - '80'
  - '--min-instances'
  - '1'
  - '--platform'
  - 'managed'
  - '--service-account'
  - '841815731741-compute@developer.gserviceaccount.com'
  - '--allow-unauthenticated'
  waitFor: ['push-image-to-container-registry']
id: 'deploy-to-cloud-run'